name: Generate README Stats

on:
  schedule:
    - cron: "42 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

# ==================== 浅色版本 ====================
      - name: Generate Light Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&exclude_repo=GenshinImpact-Client-Version,WutheringWaves-UIResources,GCResource,GCProto,SRResource,end_7z,SRProto
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Light Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=default&show_icons=true&exclude_repo=GenshinImpact-Client-Version,WutheringWaves-UIResources,GCResource,GCProto,SRResource,end_7z,SRProto
          path: profile/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # ==================== 深色版本 ====================
      - name: Generate Dark Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=github_dark&exclude_repo=GenshinImpact-Client-Version,WutheringWaves-UIResources,GCResource,GCProto,SRResource,end_7z,SRProto
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Dark Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=github_dark&show_icons=true&exclude_repo=GenshinImpact-Client-Version,WutheringWaves-UIResources,GCResource,GCProto,SRResource,end_7z,SRProto
          path: profile/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push profile/stats.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: stats-output
          build_dir: profile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
