name: wakatime stats

on:
  schedule:
    # Runs at 12am IST
    - cron: "10 */24 * * *" 
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "zh_Hans"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d-%m-%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          SYMBOL_VERSION: "3"
